In [8]:
#NumPy — the foundational package for numerical computing in Python.
#NumPy (Numerical Python) allows you to work with large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them
#Importing numpy
import numpy as np

#Creating Arrays
arr = np.array([1, 2, 3, 4])
print(arr)
#np.array(): From lists
#np.zeros(): Array of all zeros
#np.ones(): Array of all ones
#np.arange(start, stop, step): Like Python’s range()
#np.linspace(start, stop, num): Evenly spaced values
ar1 = np.zeros((2,3))
print(ar1)
ar2 = np.ones((3,2))
print(ar2)
ar3 = np.arange(0, 10, 2)
print(ar3)
ar4 = np.linspace(0, 1, 5) 
print(ar4)

#Array Indexing and Slicing
a = np.array([10, 20, 30, 40, 50])
print(a[1])     
print(a[1:4])   
#For 2D Arrays
b = np.array([[1,2,3], [4,5,6]])
print(b[1,2])   
print(b[:,1])   
print(b[0,:])  

#Basic Operations
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])
print(c + d)  
print(c * 2)   
print(c ** 2)  

#Useful array functions
arr1 = np.array([1, 2, 3, 4, 5])
print(np.mean(arr1))   
print(np.max(arr1))    
print(np.min(arr1))    
print(np.sum(arr1))    


[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
20
[20 30 40]
6
[2 5]
[1 2 3]
[5 7 9]
[2 4 6]
[1 4 9]
3.0
5
1
15


In [9]:
#Practice Exercises
#Create a 1D array of numbers from 10 to 50 with a step of 5
arr2 = np.arange(10, 50, 5)

#Create a 3x3 NumPy array filled with random integers between 1 and 100
arr4 = np.array([[2, 56, 67], [33, 77, 12], [3, 6, 89]])

#Given the array below, slice out the middle row
arr5 = np.array([[5, 10, 15],
              [20, 25, 30],
              [35, 40, 45]])
print(arr5[1,:])
#Find the mean, max, min, and standard deviation of the following array
arr6 = np.array([10, 15, 20, 25, 30, 35])
print(np.mean(arr6))
print(np.max(arr6))
print(np.min(arr6))
print(np.std(arr6))

[20 25 30]
22.5
35
10
8.539125638299666
