In [1]:
#Broadcasting lets NumPy automatically expand the dimensions of smaller arrays so operations can be performed without explicitly reshaping.
import numpy as np
#Add a scalar to a NumPy array
a = np.array([1, 2, 3])
b = 5
print(a + b)  # [6 7 8]

#Adding arrays of different shapes
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
print(a + b)


[6 7 8]
[[11 22 33]
 [14 25 36]]


In [2]:
#Aggregation Functions
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.sum(a))        
print(np.mean(a))       
print(np.min(a))        
print(np.std(a))
print(np.var(a))
print(np.max(a))

#Aggregate across rows or columns
print(np.sum(a, axis=0))  
print(np.sum(a, axis=1))  
#axis=0: Operate down columns (vertical)
#axis=1: Operate across rows (horizontal)

21
3.5
1
1.707825127659933
2.9166666666666665
6
[5 7 9]
[ 6 15]


In [7]:
#Practice Exercises
#Add 'a' and 'b' using broadcasting and print the result
a = np.array([[5, 10], [15, 20]])
b = np.array([1, 2])
print(a + b)

# Task 1: Print the sum of each row
# Task 2: Print the mean of each column
# Task 3: Print the standard deviation of the entire array
x = np.array([[4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
row_sums = np.sum(x, axis=1)
print("Sum of each row:", row_sums)
print(np.sum(x, axis=1))
print(np.mean(x, axis=0))
print(np.std(x))

[[ 6 12]
 [16 22]]
Sum of each row: [15 24 33]
[15 24 33]
[7. 8. 9.]
2.581988897471611
